eshop/account/urls.py
from django.urls import path

from . import views

app_name = 'account'

urlpatterns = [
     path('login/', views.LoginView.as_view(), name='login'),
     path('logout/', views.custom_logout, name='logout'),
     path('register/', views.register, name='register'),
     path('account/edit-user/', views.edit_user, name='edit_user'),
     # password reset urls
     path('password-reset/', views.PasswordResetView.as_view(),
          name='password_reset'),
     path('password-reset/done/', views.PasswordResetDoneView.as_view(),
          name='password_reset_done'),
     path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(),
          name='password_reset_confirm'),
     path('reset/done/', views.PasswordResetCompleteView.as_view(),
          name='password_reset_complete'),
     path('password-change/', views.password_change,
          name='password_change'),
     # orders
     path('account/orders/', views.order_list, name='order_list'),
     path('account/orders/<int:order_id>', views.order_detail,
          name='order_detail'),
     # admin panel
     path('account/admin-menu/', views.admin_menu, name='admin_menu'),
]

eshop/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
     path('', views.cart_detail, name='detail'),
     # change cart items
     path('add/<int:product_id>/', views.add_cart,
          name='add_cart'),
     path('remove/<int:product_id>/', views.remove_cart,
          name='remove_cart'),
     path('clear/', views.clear_cart,
          name='clear_cart'),
]

eshop/shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
     path('', views.product_list, name='product_list'),
     # for define category
     path('<slug:category_slug>', views.product_list,
          name='product_list_by_category'),
     path('<int:id>/<slug:slug>/', views.product_detail,
          name='product_detail'),
     path('search/<str:name>/', views.product_search,
          name='product_search'),
     path('content/<str:type>/<int:id>/', views.get_content,
          name='get_content'),
     # ADMIN
     # Product CRUD
     path('admin/product/product_list/', views.admin_product_list,
          name='admin_product_list'),
     path('admin/product/add/', views.product_add,
          name='product_add'),
     path('admin/product/update/<int:product_id>/', views.product_update,
          name='product_update'),
     path('admin/product/remove/<int:product_id>/', views.product_delete,
          name='product_delete'),
     # Category CRUD
     path('admin/category/list/', views.admin_category_list,
          name='admin_category_list'),
     path('admin/category/add/', views.category_add,
          name='category_add'),
     path('admin/category/update/<int:category_id>/', views.category_update,
          name='category_update'),
     path('admin/category/delete/<int:category_id>/', views.category_delete,
          name='category_delete'),
     # Product content
     path('admin/product/content/add/<int:product_id>/',
          views.product_content_add, name='product_content_add'),
     path('admin/product/content/delete/<int:content_id>/',
          views.product_content_delete, name='product_content_delete'),
]

eshop/shop/models.py
from unidecode import unidecode
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey

from .fields import OrderField

class SlugByNameMixin:
    """
    Mixin for generating slug by name
    """
    __slug_field_name = 'slug'
    __slug_from_field = 'name'
    
    def __slug_queryset(self, model_class, slug):
        """
        Queryset of slugs
        return queryset
        """
        slug_filter = {self.__slug_field_name: slug}
        queryset = model_class.objects.filter(**slug_filter)
        # exclude current item
        if self.pk:
            queryset = queryset.exclude(pk=self.pk)
        return queryset

    def __generate_unique_slug(self):
        """
        Generate unique slug for each item
        """
        slug_value = unidecode(getattr(self, self.__slug_from_field))
        slug = slugify(slug_value)
        num = 1
        model_class = self.__class__

        # create queryset
        queryset = self.__slug_queryset(model_class, slug)

        while queryset.exists():
            slug = f'{slug}-{num}'
            queryset = self.__slug_queryset(model_class, slug)
            num += 1

        return slug

    def save(self, *args, **kwargs):
        """
        Save item instance
        """
        if self.pk:
            try:
                # if update item
                old_instance = self.__class__.objects.get(pk=self.pk)
                old_value = getattr(old_instance, self.__slug_from_field)
                new_value = getattr(self, self.__slug_from_field)
                if old_value != new_value:
                    setattr(self, self.__slug_field_name,
                            self.__generate_unique_slug())
            except self.__class__.DoesNotExist:
                pass
        elif not getattr(self, self.__slug_field_name):
            setattr(self, self.__slug_field_name,
                    self.__generate_unique_slug())
        super().save(*args, **kwargs)

class Category(SlugByNameMixin, models.Model):
    """
    Product's category model
    """
    name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                       args=[self.slug])

class Product(SlugByNameMixin, models.Model):
    """
    Product model
    if available = False, item not selling
    fields:
        name, slug, description, category, image, price, available
    """
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    description = models.TextField(blank=True)

    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products/%Y/%m/%d')
    price = models.DecimalField(max_digits=10,
                                decimal_places=2)
    available = models.BooleanField(default=True)
    
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']), # for search and sorting
            models.Index(fields=['-created']),
        ]
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('shop:product_detail',
                       args=[self.id, self.slug])
    
class ProductContent(models.Model):
    """
    Content for product like images, videos
    Using contenttypes framework and generic foreign key
    to relate content from different tables with product
    """
    product = models.ForeignKey(Product,
                                related_name='content',
                                on_delete=models.CASCADE)
    # For content of description
    # used contenttypes framework
    content_type = models.ForeignKey(ContentType,
                                     on_delete=models.CASCADE,
                                     limit_choices_to={'model__in':(
                                        #  'text',
                                         'image',
                                         'video'
                                     )}
                                     )
    object_id = models.PositiveBigIntegerField()
    item = GenericForeignKey('content_type', 'object_id')

    def delete(self, *args, **kwargs):
        """
        Remove related object if exist
        """
        if self.item:
            self.item.delete()
        super().delete(*args, **kwargs)

    class Meta:
        indexes = [
            models.Index(fields=['content_type', 'object_id']),
        ]

# Models for content based on DescriptionBase 
# return after create admin page for products
class DescriptionBase(models.Model):
    """
    Abstract class for any content
    """
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateField(auto_now=True)

    class Meta:
        abstract = True
        
class Image(DescriptionBase):
    """
    Image content
    """
    content = models.ImageField(upload_to='products/%Y/%m/%d')

class Video(DescriptionBase):
    """
    Video content
    """
    content = models.URLField()

eshop/shop/forms.py
from django import forms

from .models import Product, Category, Image, Video
from django.core.exceptions import ValidationError
from utils.forms_utils import FormControlMixin

class ProductForm(FormControlMixin, forms.ModelForm):
    """
    Form for edit or update Product model
    set up elements for bootstrap
    """
    class Meta:
        model = Product
        fields = ['name', 'description', 'category',
                  'image', 'price', 'available']
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['available'].widget.attrs['class'] = 'form-check-input'

class CategoryForm(FormControlMixin, forms.ModelForm):
    """
    Edit category Form
    """
    class Meta:
        model = Category
        fields = ['name']
        
    def clean_name(self):
        """
        Validate name for unique
        """
        name = self.cleaned_data['name']
        print(f"DEBUG: clean_name called with: '{name}'")
        if name:
            queryset = Category.objects.filter(name__iexact=name)
            print(f"DEBUG: Found {queryset.count()} existing categories")
            if self.instance and self.instance.pk:
                print(f"DEBUG: Editing existing instance with pk: {self.instance.pk}")
                queryset = queryset.exclude(pk=self.instance.pk)
            # check unique
            if queryset.exists():
                print("DEBUG: Validation error raised") 
                raise ValidationError('Category with that name '\
                                        'already exists')
        return name


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # for inner forms
        self.fields['name'].widget.attrs['id'] = 'id_category_name'

class ImageForm(forms.ModelForm):
    """
    Form for Image model
    """
    class Meta:
        model = Image
        fields = ['content']

class VideoForm(forms.ModelForm):
    """
    Form for video model
    """
    class Meta:
        model = Video
        fields = ['content']

eshop/shop/views.py
import shop.utils as utils

from django.shortcuts import render, get_object_or_404
from django.contrib.contenttypes.models import ContentType
from django.http import JsonResponse
from django.core.paginator import Paginator
from django.db.models import Q, Count

from .models import Category, Product, Video, Image
from cart.forms import CartAddProductForm
from .admin_views import product_update, admin_product_list, product_add,\
    product_delete, category_add, category_update, admin_category_list,\
    category_delete, product_content_add, product_content_delete

def product_list(request, category_slug=None):
    """
    View products on page
    if category_slug define,
    show products in selected category
    """
    category = None
    # only categories with current available products
    categories = Category.objects.prefetch_related('products').\
        annotate(available_products=Count('products',
                                          filter=Q(products__available=True))).\
        filter(available_products__gt=0)
    products = Product.objects.filter(available=True)

    if category_slug:
        # get products from selected category
        category = get_object_or_404(Category,
                                     slug=category_slug)
        products = products.filter(category=category)

    # pagination pages
    paginator = Paginator(products, 7)
    page_number = request.GET.get('page')
    # get products from page
    products = paginator.get_page(page_number)
    
    return render(request,
                  'shop/product/product_list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})

def product_detail(request, id, slug):
    """
    View for product's details
    Display details of current product
    Args:
        id: product id
        slug: product slug
    """
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug)
    
    videos = utils.get_product_content(product, Video)
    video_images = []
    for video in videos:
        video_images.append(utils.get_video_thumbnail_url(video))
    images = utils.get_product_content(product, Image)
    
    cart_form = CartAddProductForm()
    return render(request,
                  'shop/product/product_detail.html',
                  {'product': product,
                   'images': images,
                   'video_images': video_images,
                   'videos': videos,
                   'cart_form': cart_form})

def product_search(request, name):
    """
    View for searching Product from catalog by name
    Args:
        name: name of product
    """
    products = Product.objects.filter(name__contains=name)
    paginator = Paginator(products, 20)
    page_number = request.GET.get('page')
    products = paginator.get_page(page_number)
    
    return render(request,
                  'shop/product/product_search.html',
                  {'name': name,
                   'products': products})

def get_content(request, type, id):
    """
        Get content by type
    """
    if type == 'image':
        image = get_object_or_404(Image,
                                  pk=id)
        item = utils.generate_thumbnail(image, size=(300, 300))
    elif type == 'video':
        video = get_object_or_404(Video,
                                  pk=id)
        item = video.content
    else:
        return JsonResponse({'success': False,
                             'data': 'Something went wrong'})
    return JsonResponse({'success': True,
                         'type': type,
                         'item': item},
                         status=200)

eshop/shop/templates/shop/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}Eshop{% endblock %}</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB"
      crossorigin="anonymous"/>
    <link rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI"
    crossorigin="anonymous"></script>
  </head>
  <body class="d-flex flex-column min-vh-100">
    <header class="container-fluid" id="header">
      <div
        class="row align-items-start bg-light text-white py-3"
        style="height: 75px">
        <div class="col-3">
          <a
            href="{% url 'shop:product_list' %}"
            class="btn btn-outline-primary btn-lg ms-5">
            Main
          </a>
        </div>
        <div class="col">
          <input type="text" placeholder="Search" class="form-control" id="search"/>
        </div>
        <div class="col-3 text-end">
          <div class="btn-group">
            {% if not user.is_authenticated %}
              <a href="{% url 'account:login' %}" class="btn btn-outline-primary">Login</a>
            {% else %}
              <div class="dropdown">
                <button class="btn btn-outline-primary dropdown-toggle" type="button"
                data-bs-toggle="dropdown" aria-expanded="false">
                  Menu
                </button>
                <ul class="dropdown-menu">
                  <li>
                    <a href="{% url 'account:order_list' %}" class="dropdown-item">
                      Orders
                    </a>
                  </li>
                  <li>
                    <a href="{% url 'account:edit_user' %}" class="dropdown-item">
                     Edit profile
                    </a>
                  </li>
                  {% if user.is_staff %}
                    <li>
                      <a href="{% url 'account:admin_menu' %}"
                      class="dropdown-item">
                      Admin</a>
                    </li>
                  {% endif %}
                  <li>
                    <a href="{% url 'account:logout' %}" class="dropdown-item">
                      Logout</a>
                  </li>
                </ul>
              </div>
            {% endif %}
          </div>
          {% with cart_items=cart|length %}
              <a href="{% url 'cart:detail' %}"
              class="btn btn-outline-primary position-relative me-5 ms-1">
                <i class="bi bi-cart"></i>
                {% if cart_items != 0 %}
                  <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-secondary">
                    {{ cart_items }}
                  </span>
                {% endif %}
              </a>
          {% endwith %}
        </div>
      </div>
    </header>

    <main class="flex-grow-1" id="content">
        {% block content %} {% endblock %}
    </main>

    <footer class="bg-light mt-auto" id="footer">
      <div class="container">
        <p class="text-center mb-0">
          &copy; 2024 My site. All rights is protected.
        </p>
      </div>
    </footer>
    
    <script src="//cdn.jsdelivr.net/npm/js-cookie@3.0.1/dist/js.cookie.min.js"></script>
    <script>
      // event to start searching in db
      const search = document.getElementById('search')
      search.addEventListener('keydown', function(event){
        if (event.key === 'Enter' && this.value != ''){
          const value = this.value;
          window.location.href = `/search/${value}`;
        }
      });
      
    </script>
    <script>
      document.addEventListener('DOMContentLoaded', (event) =>{
        // DOM-model loaded
        {% block domready %}
        {% endblock %}
      })
    </script>
  </body>
</html>