eshop/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
     path('', views.cart_detail, name='detail'),
     # change cart items
     path('add/<int:product_id>/', views.add_cart,
          name='add_cart'),
     path('remove/<int:product_id>/', views.remove_cart,
          name='remove_cart'),
     path('clear/', views.clear_cart,
          name='clear_cart'),
]

eshop/orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.create_order, name='create_order'),
]

eshop/cart/models.py
from django.db import models

# Create your models here.

eshop/cart/forms.py
from django import forms

# Range for quantity which can be chosen
PRODUCT_QUANTITIES = [(i, str(i)) for i in range(1,11)]

class CartAddProductForm(forms.Form):
    """
    Add or change items in cart
    override used for change items if True
    """
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITIES,
                                     coerce=int,
                                     )
    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)

eshop/cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST

from shop.models import Product
from .forms import CartAddProductForm
from .cart import Cart

@require_POST
def add_cart(request, product_id):
    """
    Add or change amount items in cart
    Args:
        request: HTTP-request
        product_id: id of product
    """
    cart = Cart(request)
    product = get_object_or_404(Product,
                                id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 override_quantity=cd['override'])
    return redirect('cart:detail')

@require_POST
def remove_cart(request, product_id):
    """
    Remove item from cart
    """
    cart = Cart(request)
    product = get_object_or_404(Product,
                                id=product_id)
    cart.remove(product)
    return redirect('cart:detail')

@require_POST
def clear_cart(request):
    """
    Clear cart from all items
    """
    cart = Cart(request)
    cart.clear()
    return redirect('shop:product_list')

def cart_detail(request):
    """
    Cart's detail
    For every item add form for update
    """
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={
            'quantity': item['quantity'],
            'override': True
        })
    return render(request, 'cart/detail.html',
                  {'cart': cart})

eshop/cart/templates/cart/detail.html
{% extends 'shop/base.html' %}
{% load thumbnail %}

{% block title %}
    Cart
{% endblock %}

{% block content %}
    {% if cart %}
    <div class="conainer mt-5 fw-bold text-start fs-6"></div>
        <table class="container border-bottom border-primary border-3">
            <tbody class="text-center">
                {% for item in cart %}
                    {% with product=item.product %}
                    <tr>
                        <td class="py-3">
                            {% thumbnail product.image 150x150 as im %}
                            <img src="{{ im.url }}">
                        </td>
                        <td class="text-start ps-5">
                            <h5>
                                <a class='text-decoration-none'
                                href="{{ product.get_absolute_url }}">
                                    {{ product.name|truncatewords:5 }}
                                </a>
                            </h5>
                            <p>{{ product.description|truncatewords:10|linebreaks }} </p>
                        </td>
                        <td>
                            <div class="btn-group">
                                <form action="{% url 'cart:add_cart' product.id %}"
                                method="POST">
                                    {% csrf_token %}
                                    {{ item.update_quantity_form.quantity }}
                                    {{ item.update_quantity_form.override }}
                                    <input class="btn btn-secondary rounded me-2"
                                    value="Update" type="submit">
                                </form>
                                <form
                                action="{% url 'cart:remove_cart' product.id %}"
                                method="post">
                                    {% csrf_token %}
                                    <input class="btn btn-danger rounded"
                                    type="submit" value="Remove">
                                </form>
                            </div>
                        </td>
                        <td>
                            ${{ item.price }} 
                            <span style="font-size:x-small">
                                per unit
                            </span>
                        </td>
                        <td class="fw-bold fs-5">
                            ${{ item.total_price }}
                        </td>
                    </tr>
                    {% endwith %}
                {% endfor %}
            </tbody>
        </table>
        <div class="container text-end mt-4">
            <p>
                In your cart {{ cart|length }}
                item{{ cart|length|pluralize:'s' }}
            </p>
            <p class="fs-4">
                Total cost: 
                <span class="fw-bold">${{ cart.total_price }}</span>
            </p>
            <div class="btn-group">
                <form method="post" action="{% url 'cart:clear_cart' %}">
                    {% csrf_token %}
                    <button class="btn btn-danger rounded me-3">
                        Clear
                    </button>
                </form>
                <a href="{% url 'orders:create_order' %}"
                class="btn btn-primary rounded">Checkout</a>
            </div>
        </div>
    {% else %}
        <h2 class="text-center mt-5">
            Your cart is empty...
        </h2>
    {% endif %}
{% endblock %}