eshop/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
     path('', views.cart_detail, name='detail'),
     # change cart items
     path('add/<int:product_id>/', views.add_cart,
          name='add_cart'),
     path('remove/<int:product_id>/', views.remove_cart,
          name='remove_cart'),
     path('clear/', views.clear_cart,
          name='clear_cart'),
]

eshop/payment/urls.py
from django.urls import path

from . import views
from .application import webhooks

app_name = 'payment'

urlpatterns = [
    path('process/', views.payment_process, name='process'),
    path('complete/', views.payment_completed, name='completed'),
    path('cancel/', views.payment_canceled, name='canceled'),
    path('annulment/', views.annulment, name='annulment'),
    # webhook
    path('webhook/', webhooks.stripe_webhook, name='stripe-webhook')
]

eshop/shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
     path('', views.product_list, name='product_list'),
     # for define category
     path('<slug:category_slug>', views.product_list,
          name='product_list_by_category'),
     path('<int:id>/<slug:slug>/', views.product_detail,
          name='product_detail'),
     path('search/<str:name>/', views.product_search,
          name='product_search'),
     path('content/<str:type>/<int:id>/', views.get_content,
          name='get_content'),
     # ADMIN
     # Product CRUD
     path('admin/product/product_list/', views.admin_product_list,
          name='admin_product_list'),
     path('admin/product/add/', views.product_add,
          name='product_add'),
     path('admin/product/update/<int:product_id>/', views.product_update,
          name='product_update'),
     path('admin/product/remove/<int:product_id>/', views.product_delete,
          name='product_delete'),
     # Category CRUD
     path('admin/category/list/', views.admin_category_list,
          name='admin_category_list'),
     path('admin/category/add/', views.category_add,
          name='category_add'),
     path('admin/category/update/<int:category_id>/', views.category_update,
          name='category_update'),
     path('admin/category/delete/<int:category_id>/', views.category_delete,
          name='category_delete'),
     # Product content
     path('admin/product/content/add/<int:product_id>/',
          views.product_content_add, name='product_content_add'),
     path('admin/product/content/delete/<int:content_id>/',
          views.product_content_delete, name='product_content_delete'),
]

eshop/payment/models.py
from django.db import models

# Create your models here.

eshop/payment/views.py
import stripe

from decimal import Decimal

from django.urls import reverse
from django.views.decorators.cache import never_cache
from django.shortcuts import render, redirect, get_object_or_404
from django.conf import settings

from orders.models import Order, OrderItem

# stripe keys from settings
stripe.api_key = settings.STRIPE_SECRET_KEY
stripe.api_version = settings.STRIPE_API_VERSION

def annulment(request):
    """
    Cancel payment before payment
    initiate by cancel on the page
    remove order_id from session
    """
    del request.session['order_id']
    return redirect('shop:product_list')

def payment_canceled(request):
    """
    Work if stripe payment was canceled
    remove order_id from session
    """
    del request.session['order_id']
    return render(request, 'payment/canceled.html')

def payment_completed(request):
    """
    Work if stripe payment was successfully completed
    """
    order_id = request.session['order_id']
    order = Order.objects.get(id=order_id)
    order.paid = True
    order.save()
    del request.session['order_id']
    return render(request, 'payment/completed.html')

# the page is not cached
@never_cache
def payment_process(request):
    """
    Start process of payment on stripe pages
    Started after order creation was successful
    use order data by order_id from current session
    """
    order_id = request.session.get('order_id', None)
    order = get_object_or_404(Order,
                              id=order_id)
    order_items = OrderItem.objects.filter(order=order).select_related('product')
    if request.method == 'POST':
        success_url = request.build_absolute_uri(reverse('payment:completed'))
        cancel_url = request.build_absolute_uri(reverse('payment:canceled'))
        # data for Stripe checkout session
        data = {
            'mode': 'payment',
            'client_reference_id': order.id,
            'success_url': success_url,
            'cancel_url': cancel_url,
            'line_items': [],
        }
        # add dynamic items
        # by data stored in the db
        for item in order.items.all():
            data['line_items'].append({
                'price_data':{
                    'unit_amount':int(item.price * Decimal('100')),
                    'currency': 'usd',
                    'product_data':{
                        'name': item.product.name,
                    },
                },
                'quantity': item.quantity,
            })
        # create Checkout session
        session = stripe.checkout.Session.create(**data)
        
        return redirect(session.url, code=303)
    else:
        return render(request, 'payment/process.html', {
            'order': order,
            'order_items': order_items,
        })

eshop/payment/templates/payment/canceled.html
{% extends 'shop/base.html' %}

{% block title %}
    Payment canceled
{% endblock %}

{% block content %}
<div class="container-fluid d-flex align-items-center justify-content-center" style="height:500px">
    <div class='position-relative bg-light p-4 rounded shadow-sm d-flex flex-column'>
        <a class="btn position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger"
        href="{% url 'shop:product_list' %}">
            <i class="bi bi-x-circle"></i>
        </a>
        <h1>Your payment hasn't been processed.</h1>
        <p>There was a problem with your payment.</p>
    </div>
</div>
{% endblock %}

eshop/payment/templates/payment/completed.html
{% extends 'shop/base.html' %}

{% block title %}
    Payment completed
{% endblock %}

{% block content %}
<div class="container-fluid d-flex align-items-center justify-content-center" style="height:500px">
    <div class='position-relative bg-light p-4 rounded shadow-sm d-flex flex-column'>
        <a class="btn position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger"
        href="{% url 'shop:product_list' %}">
            <i class="bi bi-x-circle"></i>
        </a>
        <h1>Your payment was completed</h1>
        <p>Thank you for payment! Wait your order.</p>
    </div>
</div>
{% endblock %}

eshop/payment/templates/payment/process.html
{% extends 'shop/base.html' %}
{% load thumbnail %}

{% block title %}
    Payment processing
{% endblock %}

{% block content %}
<div class="container">
    <h1 class="text-start fw-bold mt-3">Your order items:</h1>
    <table class="container-fluid mt-5">
        <thead>
            <tr class="text-center">
                <th>Image</th>
                <th>Product</th>
                <th>Quantity</th>
                <th>Total cost</th>
            </tr>
        </thead>
        <tbody class="border-bottom">
            {% for item in order_items %}
                <tr class="text-center align-middle">
                    <td class="py-3">
                        {% thumbnail item.product.image '150x150' as im %}
                        <img src="{{ im.url }}">
                    </td>
                    <td>
                        {{ item.product.name|truncatewords:4 }}
                    </td>
                    <td>
                        {{ item.quantity }}
                    </td>
                    <td class="fw-bold">
                        ${{ item.price }}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
        <tfoot>
            <tr class="pt-5 align-middle fs-4">
                <td class="text-end text-s p-3" colspan="3">
                    Total:
                </td>
                <td class="text-center fw-bold">
                    ${{ order.get_total_cost }}
                </td>
            </tr>
        </tfoot>
    </table>
    <div class="container-fluid text-end">
        <div class="btn-group mt-5">
            <a class="btn btn-danger rounded me-3"
            href="{% url 'payment:annulment' %}">Cancel</a>
            <form method="POST" action="{% url 'payment:process' %}">
                {% csrf_token %}
                <input class="btn btn-success rounded me-5" type="submit"
                value="Pay">
            </form>
        </div>
    </div>
</div>
{% endblock %}